# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'nitaym-rt'
    sourceRepo: 'default-npm-virtual'
    collectBuildInfo: true
    threads: '10'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'


- script: |
    npm run package
  displayName: 'Build the package'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'nitaym-rt'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.vsix",
            "target": "npm-default-virtual"
          }
        ]
      }
    failNoOp: true